version: "3.8"

services:
  spark:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: spark-dev
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
      - "4040:4040"
